version: "3.3"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_beer
      MYSQL_USER: springmysql
      MYSQL_PASSWORD: springmysql