rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5671:5671"
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: beer
    RABBITMQ_DEFAULT_PASS: beer
    RABBITMQ_DEFAULT_VHOST: beer