version: '3.3'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=books
      - MONGODB_PASSWORD=books
      - MONGODB_DATABASE=dbBooks